# Use official Node.js image
FROM node:18

# Set working directory inside container
WORKDIR /app

# Copy package.json & package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the project files
COPY . .

# Expose the port your app runs on (5000)
EXPOSE 5000

# Start the app
CMD ["npm", "start"]
